### ISSUE TITLE
Functional streams todo-list

### ISSUE THREAD

**Issue by dfcreative** [audiojs/contributing#20]
So since we are going to switch to pull/functional streams, there is a list to check.

* [ ] make sure all modules have main functional exports.
* [ ] make sure each module has `/pull` and `/stream` entries.
* [ ] make sure readme explains _stream_, _pull_ and no-stream ways of using.
* [ ] bump major versions.

**Comment by dy** [comment]
Obsolete — org moved past Node streams / pull-streams. ESM + direct function calls now.
